import { Delius_Swash_Caps, Sen } from "next/font/google";
import "./globals.css";

const delius = Delius_Swash_Caps({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-delius",
});

const sen = Sen({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sen",
});

export const metadata = {
  title: "OtakuFlow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${delius.variable} ${sen.variable} bg-gray-900 text-white`}
      >
        {children}
      </body>
    </html>
  );
}
